### PR TITLE
vermin 0.109.0 (new formula)

### PR DESCRIPTION
**Pull request by dawidd6**

### CODE REVIEW

**Comment by dawidd6** [comment]
Wait for: https://github.com/mhewedy/vermin/pull/24

**Comment by mhewedy** [comment]
I am glad to see this thanks 👍

**Comment by dawidd6** [comment]
@mhewedy note that this is just my personal tap, but I may consider to submit it to the core tap later.

**Comment by mhewedy** [comment]
> @mhewedy note that this is just my personal tap, but I may consider to submit it to the core tap later.

Sounds fine.

Then, how can I download it using `brew`?

**Pull request closed without merging**
